version: "3.0"
services:
  app:
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    restart: always

    env_file:
      - .env
    ports:
      - "8000:8000"
  db:
    container_name: "database"
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Daimondi12
      - POSTGRES_DB=Nevless
    ports:
      - "5432:5432"
    networks:
      - custom

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 6379:6379

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A src.routes.gifs:celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A src.routes.gifs:celery flower --port=5555
    ports:
      - "5555:5555"
    environment:
      BROKER_URL: redis://redis:6379/0
      BACKEND_URL: redis://redis:6379/0
    depends_on:
      - app
      - redis
      - celery_worker
networks:
  custom:
    driver: bridge
  rabbitmq:
    image: katanaml/rabbitmq-service
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    container_name: rabbitmq-service
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./backend-rabbitmq/etc/:/etc/backend/
      - ./backend-rabbitmq/data/:/var/lib/backend/
      - ./backend-rabbitmq/logs/:/var/log/backend/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=welcome1
      - RABBITMQ_NODENAME=rabbitnode@localhost
      - RABBITMQ_USER=skipper
      - RABBITMQ_PASSWORD=welcome1
    networks:
      - network1
    restart: always