"""comment

Revision ID: 2252c5e70dd8
Revises: af9688d1ff4b
Create Date: 2023-01-24 17:12:01.523602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2252c5e70dd8'
down_revision = 'af9688d1ff4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
