"""comment1

Revision ID: 3b707ddc56da
Revises: 2252c5e70dd8
Create Date: 2023-01-24 17:15:45.642064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b707ddc56da'
down_revision = '2252c5e70dd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
