"""comment

Revision ID: 470c774ec633
Revises: d478ec3c7655
Create Date: 2023-01-25 14:34:58.015977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '470c774ec633'
down_revision = 'd478ec3c7655'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('song_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creator', sa.String(), nullable=False),
    sa.Column('song_file', sa.String(), nullable=False),
    sa.Column('is_liked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('song_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('song_file')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
