"""comment

Revision ID: 63581e8cb848
Revises: 96f708a47930
Create Date: 2023-02-23 17:37:53.311074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63581e8cb848'
down_revision = '96f708a47930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
