"""commentik

Revision ID: 75ce1a33ef44
Revises: 3b707ddc56da
Create Date: 2023-01-24 17:24:55.717544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ce1a33ef44'
down_revision = '3b707ddc56da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
