"""comment

Revision ID: 7fdf29f4f14e
Revises: 63581e8cb848
Create Date: 2023-03-02 16:27:02.351217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdf29f4f14e'
down_revision = '63581e8cb848'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
