"""comment

Revision ID: 88376cadddd9
Revises: 256b1c80007a
Create Date: 2023-01-23 17:17:22.588749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88376cadddd9'
down_revision = '256b1c80007a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('song_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creator', sa.String(), nullable=False),
    sa.Column('is_liked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('song_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
