"""comment

Revision ID: b0ffb328f7ef
Revises: b8c449d37504
Create Date: 2023-01-26 02:45:44.613027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ffb328f7ef'
down_revision = 'b8c449d37504'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
